### ISSUE TITLE
9/25 processing: incorrect assignments

### ISSUE THREAD

**Issue by izaslavsky** [CINERGI/ontology_cleanup#1]
Notes in https://www.copy.com/s/t%3A4KOCBlRYFsar9GGv%3Bp%3A%252FScience%2520Base%2520Documents%2520Review%2520Notes
Files in Copy\SDSC_SPATIAL\ANNOTATION\files_to_compare\sample_docs_sciencebase_kw_09_25_2015\kw2
- [ ] Heat:     Property>Measure (should be property - other)
- [ ] Geothermal as property -measure. Should become "geothermal feature", and only exist under "geologic feature"
- [x] MERCURY   Equipment>Platform (Burak is working on a general rule for capitalized labels marked as equipment)
  PATH    Equipment>Satellites
  IMPROVE Equipment>Platform
- [ ] Circulation   Property>Measure (should be a process)
- [ ] Climate Change marked as Science Domain>Climate, should be marked as Process

**Comment by bozyurt** [comment]
General rule for capitalized labels marked as equipment seems to be working based on initial tests.
