### ISSUE TITLE
10/2 processing: incorrect assignments

### ISSUE THREAD

**Issue by agiliarini** [CINERGI/ontology_cleanup#6]
- [ ] Geothermal Feature as Property>Measure is incorrect 
- [x] Heat was marked as Property>Measure, should be Property>Other
- [x] Circulation was marked as Property>Measure, should be a Process
- [x] Water Quality was marked as Property>Measure, should be Property>Other 
- [x] Climate Change was marked as Science Domain>Climate, should be Process>Atmospheric Process 

Dissolved Solid was marked as Material>Chemical Substance (not sure if this correct or not)

**Comment by smrgeoinfo** [comment]
dissolved solid as chemical substance is probably good enough. I can't think of any better treatment...

**Comment by valentinedwv** [comment]
# 4f4e4abbe4b07f02db6725b6

River added a Keyword. Should not be. Location Name is Raft River
Raft River Geothermal Area, Idaho;

# 4f4e4a57e4b07f02db62df65

Thermal loading of natural streams
Talking about the Atmospheric conditions, not geothermal.
Might work better if abstract is added:
http://pubs.er.usgs.gov/publication/pp991

**Comment by adamschachne** [comment]
Geothermal (Geothermal Feature) has the path Feature > Geologic Feature > Geothermal. It should be marked as a Feature. I have left it as is.
