### ISSUE TITLE
10/9 processing (NOAA): incorrect assignments

### ISSUE THREAD

**Issue by agiliarini** [CINERGI/ontology_cleanup#9]
- [ ] Island as Feature>Geologic Feature seems more fitting than Feature>Hydrologic Feature
- [x] Seep as Feature>Hydrologic Feature is correct, but in context it was "Petroleum Seep". So, should be Petroleum Seep as Feature>Physiographic Feature

**Comment by adamschachne** [comment]
"Island" (http://yago-knowledge.org/resource/geoclass_island) has cinergiParent "Marine Feature" (http://hydro10.sdsc.edu/cinergi_ontology/cinergi.owl#Marine_Feature)
